### ISSUE TITLE
Randomize default seasons

### ISSUE THREAD

**Issue by jangler** [jangler/oos-randomizer#16]
This would probably take place in a setup step before the slotting algorithm runs, since I'm not sure if slotting seasons makes sense.

For convenience, the seasons in areas with seed trees could be synced to the season that the seeds grow in, like they are in the vanilla game.

**Comment by Drenn1** [comment]
Or allow seeds to grow in any season.

Maybe if seasons are slotted, the prenodes could look like this?

```
"lake winter": Or("winter", "lake winter default")
"lake portal 1": And("eyeglass lake", "flippers", "lake winter"),
"lake portal 2": And("eyeglass lake", "pegasus jump L-2", "lake winter"),
```

Then at the end, you can assign the season for any unassigned slots. Though granted, I'm not sure how it would mix with the "chest assignment" code. If it helps, maybe they could be thought of as if they're "items" that you start with?

In any case, I'm not sure whether the randomization produced would be better than just doing it at the start, since I don't understand the graph traversal stuff too well.

**Comment by Drenn1** [comment]
I think process of elimination would get a bit annoying after a while. How many screen transitions would it take to check all seasons on all trees? It should be possible to change the treetop graphics, assuming the number of ember trees does not decrease, so then you'd just need to memorize what season that seed type needs.

I think it would be more interesting if the season were randomized independently of the tree, just so that those two things are "decoupled" producing more random possibilities. For example, spool swamp defaulting to winter, and north horon defaulting to summer, both open up routes; it would be nice if that was decoupled from the type of seed you get.

**Comment by Drenn1** [comment]
In terms of changing treetop graphics, look up "treeGfxLocationsTable" in the disassembly.

**Comment by jangler** [comment]
Yeah, same number of each type of tree. Definitely more interesting to decouple it, I agree. And changing the actual graphics is a very good idea :P

**Comment by jangler** [comment]
Implemented in https://github.com/jangler/oos-randomizer/commit/a3b8e0215d8c3acff99d471dacf6ed2b650790fd and https://github.com/jangler/oos-randomizer/commit/2125c412335cf0abcc14a80fd9f61025ff3d9045.
