### ISSUE TITLE
warping to start as a softlock safeguard

### ISSUE THREAD

**Issue by churine** [jangler/oos-randomizer#34]
a solution I've seen to prevent softlocks (and to cut backtracking teduim) is to allow warping back to the starting screen (i.e. where Impa is)
link's awakening randomizer does this by adding extra cave entrances on some locations

but if it were possible, maybe some button combination (changing the soft reset to this? something in the map screen?) or some menu option could work better

this would allow logic to disregard needing to get out of places and open it up, and not need to adjust areas to let you escape them

**Comment by jangler** [comment]
As clumsy as start warping is and as much as I dislike it, I admit it would be useful, since people are always discovering new ways to softlock—and I anticipate more ways will emerge as more things become randomized. But the implementation is tricky.

Adding extra cave entrances in some locations would require adding interactions, which would be difficult since the randomizer does not disassemble/recompile the ROM to any degree, just change some bytes here and there. Wouldn't that require anticipating where softlocks could happen anyway?

Changing soft reset would be a big no-no since it's in speedrunner muscle memory to do it 30 times per run. Actual save and quit is never used, though, so replacing the graphics for that option with English "start warp" text could be a viable option. There's probably enough S+Q code that it could be replaced with start warp code.

**Comment by jangler** [comment]
Implemented in https://github.com/jangler/oos-randomizer/commit/e7672fa0256a0a60f87b697297a23f1bcf8ac196. I hate it but it's there now.
