### ISSUE TITLE
L2 Boomerang Doesn't Wake Up The Maku Tree

### ISSUE THREAD

**Issue by raekuul** [jangler/oos-randomizer#38]
[oos-randomizer_log_2018-08-11_080720.txt](https://github.com/jangler/oos-randomizer/files/2280230/oos-randomizer_log_2018-08-11_080720.txt)

I'll go through my completed vanilla game tonight to see which items can and can't wake up the Maku tree. The L-2 Boomerang is not one of them (or I'm doing something wrong).

E: Bombs do work but the timing isn't obvious so players could theoretically waste their ten "free" bombs trying to wake up the Maku Tree. Also not all casuals would think to try them (as I didn't).

Further Edit: Actually, it looks like the only items that can't wake up the Maku Tree are the bracelet, feather/cape, shovel, and the boomerangs, so maybe add a note to the readme file about using bombs to wake up the Maku tree?

Yet another edit: It looks like the Bracelet's locked behind itself again anyway (it's in the Square Jewel Chest) - I need the bracelet to leave town from the north (Blaino's got the flippers, which you can loop around the Moblin's Fortress to get there if you've got your animal companion (NOTE: or the Cape and Pegasus seeds if you have Moosh as your companion, or the Flippers if Ricky is your companion), but you still need to access Spool Swamp to activate animal companions, and you'd still need to have ember seeds and a feather) or to enter Spool from Subrosia, and I need ember seeds from the Spool Swamp tree to exit town from the east, and I need a feather to get into Subrosia from town anyway (which the nearest feather is... behind the ember seeds, which are growing in Spool Swamp)

**Comment by jangler** [comment]
IMO L-2 boomerang is a pretty nice starting item since you can get the 30 rupee chest in hero's cave with it (same deal with bracelet), which is enough for bombs and for Blaino. L-1 boomerang, on the other hand, is a terrible starting item. The items that can and can't wake up the Maku Tree are in the logic already; I tested them all, and yes, nearly everything works.

But yes, you are expected to use bombs if you don't get a starting item that pops the bubble. In fact, you can be expected to do D1 up to the dungeon item with bombs as your only weapon. The randomizer doesn't expect you to do extremely difficult tricks like HSS skip, poe skip, or magnetless D7, but it does expect you to do some less difficult speedrun/non-casual strats and it does expect you to be inventive. Other people have also expressed confusion over the boomerangs as starting items, so I *could* put a note in the readme, but by that logic I should be putting a lot of weird things in the readme, like how you can kill the moblins across the gap in D2 by throwing a pot from the previous room, or how you can push enemies into pits using the shovel, or how you can use scent seeds from a satchel as a weapon.

Sorry about the bracelet in the square jewel chest; that problem is specific to that chest and was fixed in 1.3.1 yesterday.

**Comment by raekuul** [comment]
I'd suggest just a note about waking the Maku tree with bombs, framed as an example of the necessary creative thinking.

**Comment by jangler** [comment]
Added FAQ to readme in https://github.com/jangler/oos-randomizer/commit/dde06bb1542888e3faec77e1ca1363a4acc8ee2b.
