### ISSUE TITLE
Natzu River/Prairie/Wasteland Navigation Notes

### ISSUE THREAD

**Issue by raekuul** [jangler/oos-randomizer#39]
You must have Ricky to navigate through Natzu Prairie if you don't get any other companion's flute first, due to the cliffs (though you can access Moblin's Keep with Feather + Flippers from the Sunken City side). Ricky is the default companion, and you get his flute if you have no flute when he takes you to Spool Swamp.

 You can navigate Natzu Wasteland without Moosh using the Roc's Cape (and can explore it in total with Cape and Pegasus Seeds), and can access Moblin's Keep with Cape + Flippers. Moosh's flute is obtainable from the Horon village shop for 150 Rupees, and is the suggested flute when the Cape appears early.

You can navigate Natzu River without Dimitri using the Flippers, but you won't be able to access Moblin's Keep without him (due to the current). Dimitri has the secondary advantage of providing access to the Subrosian Lava Lake without flippers, allowing for acquiring Autumn with just Feather and Bracelet (and a 2-pit jump to cross from Great Furnace area to the southern Village area). Dimitri's flute is the flute obtained from Subrosian Dancing, and is the suggested flute when the Flippers appear early. 

Activating the Animal Companion requires either Spool Swamp access (for Dmitri and Moosh) or taking Ricky to Spool Swamp after retrieving his gloves, depending on which animal companion you want. Moosh (or rather, Natzu Wasteland) provides the most freedom in movement, while Dimitri allows for more access overall.

Natzu's form does not become locked until you obtain one of the three flutes (so it's plausible to have a seed where the Roc's Cape is stashed away in Moblin's Keep and you get the Bracelet from Blaino, later on down the line when heart piece locations are shuffled in)

**Comment by jangler** [comment]
The animal flutes are used pretty scarcely in the logic right now because of cases like this, where it's possible to lock yourself out of some possibilities by getting the wrong flute. For instance, only Ricky and Moosh can jump over the pits in North Horon, so technically their (identified) flutes satisfy the requirements for that obstacle, but if you get Dimitri's flute then your only option is feather/cape and there's no going back.

In practice, even Ricky's gloves are rarely slotted as a non-filler item by the randomizer because it's possible to get to Sunken City via the staircase in Eastern Suburbs.

**Comment by jangler** [comment]
I mean the pits near Eyeglass Lake, not the ones that you use Ricky to jump over in a regular playthrough.
