### ISSUE TITLE
H&S Softlocked

### ISSUE THREAD

**Issue by SlickYoshi** [jangler/oos-randomizer#49]
I was wondering how possible it was to remove the H&S cutscene. Given a pegasus + cape skip, it's very easy to get yourself softlocked, should you not get the shovel early on. While H&S is entirely avoidable on most seeds, it could still cause trouble for the careless. If it is possible, I don't expect any priority on it due to it being avoidable, but it would be a nice quality of life upgrade.

**Comment by jangler** [comment]
If you have a seed where you can get to H&S without shovel, show me. But there's a logic check in place which should prevent that from ever happening.

**Comment by raekuul** [comment]
This is actually something I've been thinking about. You can get in minimally with either cape and pegasus seeds, or L2 Boomerang and roc's feather (you need jumping to get in no matter which route you take). 
Aside from filler for Spring Tower, what does the theft of the feather and subsequent required H&S bring to the game?

**Comment by jangler** [comment]
As with all nuisances that aren't strictly mandatory, routing choices. There are seeds in which you only have feather, and have to weigh the known cost of H&S against the unknown cost of trying to find the means to skip it later.

**Comment by raekuul** [comment]
I agree with that reasoning in the short term (the main thing I would like Forced H&S removed over is the convenience of the Mount Cuccoo portal, though there's a lot of item and routing combinations that would open up from removing it as well), but leaving the feather confiscation script in the game is going to lead to continual "I can't finish Hide and Seek because I don't have the shovel" complaints.

**Comment by jangler** [comment]
In any case, the answer to "how possible is it?" is that it would be very easy to do, and I've found that bending the game is sometimes nicer than bending the randomizer. But in this case I'd be more inclined to prevent the feather from being *buried* rather than prevent it from being stolen.

And in case there's some misunderstanding over this, the reason Rosa's sequence was removed from the overworld was due to a softlock from dying / s+q'ing and respawning stuck in a tree after exiting Subrosia via that portal before it was activated, not because the sequence was annoying. 🙃

**Comment by raekuul** [comment]
My main issue with the second one is that it's just padding - Rosa H&S at least is introducing you to Subrosians in general as well as telling you where the Temple of Seasons actually *went*. All Treasure H&S does is highlight just how integral jumping is to the GB Zelda games.

**Comment by raekuul** [comment]
I'm trying to think of how that last one would even come about. You'd need bracelet and feather and access to the eastern suburbs, *and* you'd need for that to be your Spool Swamp access (and on top of that, the floodgate *itself* stops you from getting anything in spool swamp other than the cave in picture two anyway). Pretty much the only way it could happen is if the floodgate key itself (or progression towards it) was in that one cave, and it's locked behind the shovel anyway at that point. 

(I'm half-tempted to jokingly suggest adding the Shovel as a starting item a la the swords in a linked game, but that would probably make things worse rather than better)

**Comment by jangler** [comment]
One scenario for the second one is getting summer rod -> bracelet -> flippers -> floodgate key with Spool Swamp defaulting to winter. You could change the season to summer, enter Subrosia, get absolutely nowhere, and be trapped by the pits and snow piles when you leave and the season resets.

**Comment by raekuul** [comment]
I've been completely spoiled by LttP Rando; I'm used to being able to S&Q back to Link's House/Sanctuary/the Pyramid in situations like that. I keep forgetting that the GB Zeldas tie your save to the last OW door you've used.

**Comment by raekuul** [comment]
I would assume from Farore spawning a chest with variable contents based on what password you tell her in a linked game that a chest with variable contents could also be spawned after completing Treasure H&S (that's effectively what the game does in vanilla, only with a dig spot instead of an actual box).

**Comment by SlickYoshi** [comment]
Yeah, the Rosa Gasha chest is the one by the long stairs, almost directly north of the Subrosian Chef, as I recall.

**Comment by jangler** [comment]
It's actually as easy as changing one byte: https://gfycat.com/TediousArtisticArrowcrab

**Comment by jangler** [comment]
Also yes, something is very wrong with that seed if it thinks that H&S is locked behind shovel.
