### ISSUE TITLE
[Crash, forced Hardware Reset] Bombs from Ring Chest

### ISSUE THREAD

**Issue by WashedUpLinkshot** [jangler/oos-randomizer#50]
the swap "d7 ring chest <- bombs, 10" played the ammo pickup sfx, did not bring up a text box nor item sprite, and did not unpause the game.

similarly, on Aug 19th, "d2 10-rupee chest <- compass" produced the crash but did draw the Compass. I forgot to report this when it happened.

**Comment by WashedUpLinkshot** [comment]
[D7 Crash](https://github.com/jangler/oos-randomizer/files/2316537/oos-randomizer_log_2018-08-23_171618.txt)
[D2 Crash](https://github.com/jangler/oos-randomizer/files/2316538/oos-randomizer_log_2018-08-19_234719.txt)

**Comment by jangler** [comment]
US version then?

**Comment by jangler** [comment]
The D2 crash was fixed in 1.5.2; the problem was that the compass was also placed where the satchel was, giving it a collection mode incompatible with chests.

Bombs in the ring chest in the D7 crash seed work fine for me, so I think your problem was actually with fool's ore in the map chest, which was fixed in 1.5.3.
