### ISSUE TITLE
Add Items from Ages

### ISSUE THREAD

**Issue by isaacbunsen** [jangler/oos-randomizer#72]
Would it be feasible to put things like the switch-hook and the cane of somaria from ages into seasons?
Ages rings?
Only items that are applicable to seasons' assets I suppose.
You'd have to account for the 16 item limit.
Thoughts?

**Comment by jangler** [comment]
Ages rings are entirely possible since you can already get them by transferring them through one of Vasu's snakes in a linked game, but including them in the item pool would require replacing the existing rings, which would break from the current ideology (for lack of a better word) of the randomizer.

Ages items are not really feasible, no. In a full disassembly, probably, but they're pretty far beyond the scope of what the randomizer is designed or intended for.
